### ISSUE TITLE
Killing capture with nmap.

### ISSUE THREAD

**Issue by picatz** [sdaubert/packetgen#37] opened 2017-02-24 20:28 UTC
While running this script:
```ruby
require 'packetgen'

ipv4 = 0
ipv6 = 0
other = 0

PacketGen.capture('en0', promisc: true) do |packet|
  if packet.is? 'IP'
    ipv4 += 1
  elsif packet.is? 'IPv6'
    ipv6 += 1
  else
    other += 1
  end    
  print "IPv4: #{ipv4} , IPv6: #{ipv6} , OTHER: #{other} \r"
end
```

If I run nmap in another shell:
```shell
$ nmap 192.168.0.0/24
```

I will get ( after a couple of seconds ):
```
/usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.0/lib/packetgen/packet.rb:244:in `parse': cannot identify first header in string (PacketGen::ParseError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.0/lib/packetgen/packet.rb:68:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.0/lib/packetgen/capture.rb:54:in `block (2 levels) in start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.0/lib/packetgen/capture.rb:51:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/packetgen-1.4.0/lib/packetgen/capture.rb:51:in `block in start'
```

So, this seems to be tied to the fact that there are invalid packets being sent. Though, I think for the capture, should there be a graceful failure for these things, or an option to fail a little more gracefully and allow capturing to continue even if there's a failure? Perhaps classify the packet as an invalid packet type?

**Comment by picatz** [comment] 2017-02-24 20:31
I could try to work on the PR if you don't have the time to do so. I image some sort of begin/rescue magic in the packet parsing for the capture method? I realize you've put in a whole bunch of work already. Maybe you'll have a better way of working fixing this.

**Comment by sdaubert** [comment] 2017-02-26 15:05
I cannot reproduce your test case: after 1 hour, there is no error.
Which version do you use?
V1.4.0 introduces some protocols (Wi-Fi with low level protocols as PPI or RadioTap, which may be instanciated as they are difficult to differentiate from noise).

**Comment by picatz** [comment] 2017-02-26 15:44
`Nmap 7.40` and `PacketGen::VERSION 1.4.0`

**Comment by picatz** [comment] 2017-02-26 16:09
Give me a little bit and I'll see if I can provide some better context for you.

**Comment by picatz** [comment] 2017-02-26 16:40
## When I can't even reproduce my own error
![knows_the_feel](https://cloud.githubusercontent.com/assets/14850816/23341560/de423bf2-fc17-11e6-836b-50b8a4d210ed.gif)

I swear I was able to reproduce this before. I dunno.

_I promise I wasn't trying to waste your time._

If I somehow magically do this again -- um, I guess I'll let you know?

**Comment by sdaubert** [comment] 2017-02-26 19:57
OK. I close it. Open it again if you can reproduce it.

**Closed by sdaubert** 2017-02-26 19:57 UTC
Labels: invalid
